// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-S488tvDxJweYtcAW4dX50agZfk80764',
    appId: '1:209763699835:android:4bb4c3d5f50cb70788e6de',
    messagingSenderId: '209763699835',
    projectId: 'vegifreshbyminglebytes',
    storageBucket: 'vegifreshbyminglebytes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMtqILk1zeiLP7A7KlDeLm5ZLDJqfOWH8',
    appId: '1:209763699835:ios:1d2d7ea2864dbf1888e6de',
    messagingSenderId: '209763699835',
    projectId: 'vegifreshbyminglebytes',
    storageBucket: 'vegifreshbyminglebytes.appspot.com',
    androidClientId: '209763699835-7p0bm6e20ddp6559h4i0picaen0ha7ua.apps.googleusercontent.com',
    iosClientId: '209763699835-h6816aafigbl5k8mg1sed3tk92rqqq5e.apps.googleusercontent.com',
    iosBundleId: 'com.minglebytes.vegifresh',
  );
}
